name: Generate Changelog

on:
  push:
    branches:
      - main

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine version
        id: version
        run: |
          latest_tag=$(git describe --tags --abbrev=0 || echo "0.0.0")
          new_version=$(echo $latest_tag | awk -F. '{print $1"."$2+1"."$3}')
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV

      - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: .github/cliff.toml
          args: --verbose --bump --tag ${{ env.NEW_VERSION }}
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Commit
        run: |
          git checkout main
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          set +e
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md for $NEW_VERSION"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git main

      - name: Create and push tag
        run: |
          git tag $NEW_VERSION
          git push origin $NEW_VERSION
