name: CI/CD Pipeline

on:
  push:
    branches:
      - "**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check dags/ and spark/ directories
        run: |
          if [ ! -d "dags" ] || [ ! -d "spark" ]; then
            echo "Error: Required directories missing!"
            exit 1
          fi
          echo "✅ Directories exist!"

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    if: ${{ !startsWith(github.ref, 'refs/heads/feature/') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: |
          docker build -t my-airflow-image .

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: contains(fromJson('["refs/heads/main", "refs/heads/master", "refs/heads/develop"]'), github.ref)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set environment variables
        run: |
          echo "AIRFLOW_UID=$(id -u)" >> .env
          echo "AIRFLOW_GID=$(id -g)" >> .env
          echo "✅ Environment variables set"

      - name: Deploy image
        run: |
          docker-compose up -d
